namespace Blake.BuildTools.Generator;

public static class SampleContentBuilder
{
    public static async Task InitSampleContent(string projectFilePath)
    {
        var pagesFolder = Path.Combine(Path.GetDirectoryName(projectFilePath) ?? string.Empty, "Pages");
        if (!Directory.Exists(pagesFolder))
        {
            Directory.CreateDirectory(pagesFolder);
        }

        var samplePagePath = Path.Combine(pagesFolder, "SamplePage.md");

        if (!File.Exists(samplePagePath))
        {
            await File.WriteAllTextAsync(samplePagePath, SamplePageContent);
            Console.WriteLine($"✅ Sample page created at: {samplePagePath}");
        }
        else
        {
            Console.WriteLine($"⚠️  Sample page already exists at: {samplePagePath}");
        }

        // Add sample template
        var templatePath = Path.Combine(pagesFolder, "template.razor");
        if (!File.Exists(templatePath))
        {
            await File.WriteAllTextAsync(templatePath, SampleTemplate);
            Console.WriteLine($"✅ Sample template created at: {templatePath}");
        }
        else
        {
            Console.WriteLine($"⚠️  Sample template already exists at: {templatePath}");
        }

        // update the nav menu
        var navMenuPath = Path.Combine(Path.GetDirectoryName(projectFilePath) ?? string.Empty, "Layout", "NavMenu.razor");

        if (File.Exists(navMenuPath))
        {
            var navMenuContent = await File.ReadAllTextAsync(navMenuPath);
            if (navMenuContent.Contains("</nav>"))
            {
                // Insert the new menu item before the closing </nav> tag
                const string newMenuItem = """
                                                   @foreach (var content in GeneratedContentIndex.GetPages())
                                                   {
                                                       <div class="nav-item px-3">
                                                           <NavLink class="nav-link" href="@(content.Slug)">
                                                               <span class="@(content.IconIdentifier)" aria-hidden="true"></span> @content.Title
                                                           </NavLink>
                                                       </div>
                                                   }
                                           """;

                var insertIndex = navMenuContent.LastIndexOf("</nav>", StringComparison.Ordinal);

                if (insertIndex != -1)
                {
                    navMenuContent = navMenuContent.Insert(insertIndex, $"{Environment.NewLine}{newMenuItem}{Environment.NewLine}");
                    await File.WriteAllTextAsync(navMenuPath, navMenuContent);
                    Console.WriteLine($"✅ Updated NavMenu.razor with dynamic content links.");
                }
                else
                {
                    Console.WriteLine("⚠️  Could not find </nav> tag in NavMenu.razor to insert dynamic content links.");
                }
            }
        }
    }

    private const string SamplePageContent = """
                                             ---
                                             title: 'My first test page'
                                             date: 2025-07-16
                                             image: images/blake-logo.png
                                             tags: ["non-technical", "personal", "career", "community"]
                                             description: "Get to know the fundamentals of Blake, the static site generator."
                                             iconIdentifier: "bi bi-plus-square-fill-nav-menu"
                                             ---

                                             ## Hello world!

                                             Hello. This is a test page, generated by the Blake Blazor static site generator. Like it?

                                             ## FAQ

                                             1. Why?

                                             I...honestly can't remember!

                                             2. What's next?

                                             Templating system...other features...I forget. I have a roadmap though.

                                             3. How do I use it?

                                             Eventually it will be a standalone CLI tool, you'll be able to use it like this:

                                             ```bash
                                             blake init
                                             blake bake
                                             dotnet run
                                             ```

                                             ## Roadmap

                                             ```bash
                                             blake new --template my-template
                                             blake new -t a-different-template
                                             ```

                                             """;
    private const string SampleTemplate = """
                                                <PageTitle>@Title</PageTitle>
                                                
                                                <p>
                                                    Published on: @Published
                                                </p>
                                                
                                                <p>
                                                    @Description
                                                </p>
                                                
                                                @Body
                                                
                                                @code {
                                                
                                                }
                                                """;
}
